spring.application.name=finance-api
spring.datasource.url=jdbc:postgresql://localhost:5432/finance
spring.datasource.username=postgres
spring.datasource.password=matheus
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=dev
spring.devtools.restart.enabled=true